### ISSUE TITLE
Won't install for me

### ISSUE THREAD

**Issue by CJ-Johnson** [taaem/nodejs-linux-installer#5]
I'm running Debian but I can't seem to install it at all. I'm SSHing into the terminal, but that shouldn't have any effect. I think it even quit before completing, but I'm not sure.

Here's the console output: http://pastebin.com/R0JEaJDV

Can you tell me what I'm doing wrong?

**Comment by woverton** [comment]
This is likely because of the https cert for the wgets. try running

```
wget --output-document=node-updater.html https://nodejs.org/dist/latest/
```

**Comment by taaem** [comment]
If you are still interested I changed many things maybe it now works for you
